// Generated by scripts/build-resume-preview.sh. Do not edit by hand.
//
// The preview on /resume is a raster of the PDF rather than the PDF itself,
// because a browser's built-in viewer surrounds the page with its own grey
// chrome and toolbar, which took up more room than the resume did.
//
// A picture of a document goes stale the moment the document changes, so
// RESUME_PDF_SHA256 records which PDF this image was built from and
// resumePreview.test.ts fails when they no longer match. Regenerate with
// `npm run resume:preview`.

export const RESUME_PDF = '/Blake_Grudzien_Resume.pdf'
export const RESUME_PREVIEW = '/Blake_Grudzien_Resume.webp'
export const RESUME_PREVIEW_WIDTH = 1700
export const RESUME_PREVIEW_HEIGHT = 2200
export const RESUME_PDF_SHA256 =
  '62510bb3ef93642e4ccea5dfcd2b84e1dc075487661d7209b133f83e06d10089'
