#!/usr/bin/env bash
# Rasterises the resume PDF into the preview image shown on /resume, and
# records which PDF it was made from.
#
# The preview is a picture of the PDF, so it goes stale the moment the PDF
# changes. resumePreview.test.ts compares the recorded hash against the
# actual PDF and fails if they have drifted, so run this every time the
# resume is replaced.
#
# Needs poppler (pdftoppm) and webp (cwebp):  brew install poppler webp
set -euo pipefail

cd "$(dirname "$0")/.."

PDF="public/Blake_Grudzien_Resume.pdf"
OUT="public/Blake_Grudzien_Resume.webp"
CONST="src/pages/resume/resumePreview.ts"
# 200 DPI so the page stays sharp on a high-density screen at the width it
# is displayed; q68 because text compresses well and the difference above
# that is invisible while the file keeps growing.
DPI=200
QUALITY=68

for tool in pdftoppm cwebp; do
  command -v "$tool" >/dev/null || { echo "Missing $tool. brew install poppler webp" >&2; exit 1; }
done
[ -f "$PDF" ] || { echo "No $PDF" >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

pdftoppm -png -r "$DPI" -singlefile "$PDF" "$TMP/page" 2>/dev/null
cwebp -q "$QUALITY" "$TMP/page.png" -o "$OUT" >/dev/null 2>&1

WIDTH=$(sips -g pixelWidth "$TMP/page.png" | awk '/pixelWidth/{print $2}')
HEIGHT=$(sips -g pixelHeight "$TMP/page.png" | awk '/pixelHeight/{print $2}')
HASH=$(shasum -a 256 "$PDF" | awk '{print $1}')

cat > "$CONST" <<TS
// Generated by scripts/build-resume-preview.sh. Do not edit by hand.
//
// The preview on /resume is a raster of the PDF rather than the PDF itself,
// because a browser's built-in viewer surrounds the page with its own grey
// chrome and toolbar, which took up more room than the resume did.
//
// A picture of a document goes stale the moment the document changes, so
// RESUME_PDF_SHA256 records which PDF this image was built from and
// resumePreview.test.ts fails when they no longer match. Regenerate with
// \`npm run resume:preview\`.

export const RESUME_PDF = '/Blake_Grudzien_Resume.pdf'
export const RESUME_PREVIEW = '/Blake_Grudzien_Resume.webp'
export const RESUME_PREVIEW_WIDTH = $WIDTH
export const RESUME_PREVIEW_HEIGHT = $HEIGHT
export const RESUME_PDF_SHA256 =
  '$HASH'
TS

echo "wrote $OUT ($(du -h "$OUT" | cut -f1), ${WIDTH}x${HEIGHT})"
echo "wrote $CONST"
